Repository githubschool/biz-dev, pull requests merged in 2020-11, with the labels that each got.

#9 Updated ISDRizO-br file in Git Hub-- this is pull request
  _slides/03-ISDRizO.md
Labels: Git hub training

#10 Corrected the caption to match the picture
  _slides/04-ISDSonLe.md
Labels: caption-project, documentation

#12 JIRA-123: This PR updates the caption to be more descriptive
  _slides/02-ericalloyd.md
Labels: caption-project, documentation

#17 Natnaelfufa isd caption
  _slides/06-NatnaelFufa-ISD.md
Labels: caption-project

#15 This PR updates the caption - dwoo on Nov 17 2020
  _slides/14-dwooatisdlacountygov.md
Labels: caption-project, documentation

#13 PR for dabarton Update caption
  _slides/09-dabarton.md
Labels: caption-project, documentation
